### PR TITLE
Added necessary .gitignore file

### PR DESCRIPTION
**Pull request by Zildj1an**
Request autogenerated with https://github.com/Zildj1an/ignores

Signed-off-by: Carlos Bilbao <bilbao@vt.edu>

### CODE REVIEW

**Comment by stof** [comment]
This repo is my personal fork used to send PRs upstream. There is no point submitting PRs here. Your autogenerated PRs will be annoying more than useful.

**Comment by Zildj1an** [comment]
Annoying to some, helpful to others, I would argue. Regardless, thanks for the feedback!

**Comment by stof** [comment]
@Zildj1an a fork is not meant to add such ignore rule by diverging from the original repo. That only makes the fork harder to use to contribute upstream due to actually forking the main branch with a different history.
If you still want to run such automated PR generation (which I would probably still find annoying to be honest), you should at least ignore fork repositories.

**Comment by Zildj1an** [comment]
Ignoring forked repos is a good idea, will do

**Pull request closed without merging**
